[package]
name = "pilm"
version = "1.1.1"
compiler = "0.11.0"
entrypoint = "lib.typ"
repository = "https://github.com/patricoferris/typst-template"
license = "MIT-0"
description = "Versatile and minimal template for non-fiction writing. Ideal for class notes, reports, and books"
keywords = ["notes", "script", "report", "book", "novel", "non-fiction", "running footer", "class", "lecture"]
categories = ["book", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
